"""Download the latin-subset .woff2 files for the three QuickQuote fonts and
write src/_fonts.css with @font-face declarations pointing at /fonts/*.

Run from the repo root:
    py scripts/fetch-fonts.py

Re-run any time you bump weights or the Google Fonts URLs change. The script
is idempotent — woff2 files are overwritten if names match.

Why latin only: QuickQuote is an internal English-only app. Google's full
multi-subset CSS would pull ~84 files (12 weights x 7 unicode subsets);
latin alone is 12 files and covers everything we actually render.
"""

from __future__ import annotations

import os
import re
import sys
import urllib.request

GOOGLE_CSS_URL = (
    'https://fonts.googleapis.com/css2'
    '?family=Inter+Tight:wght@400;500;600;700;800;900'
    '&family=JetBrains+Mono:wght@400;500;600'
    '&family=Source+Serif+4:wght@400;600;700'
    '&display=swap'
)
# Google Fonts varies its CSS by User-Agent; a Chrome-shaped UA gets the
# woff2-only response we want.
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(ROOT, 'public', 'fonts')
OUT_CSS = os.path.join(ROOT, 'src', '_fonts.css')


def fetch_css() -> str:
    req = urllib.request.Request(GOOGLE_CSS_URL, headers={'User-Agent': UA})
    with urllib.request.urlopen(req) as r:
        return r.read().decode('utf-8')


def main() -> None:
    os.makedirs(FONTS_DIR, exist_ok=True)
    css = fetch_css()

    # Each subset is a `/* <subset> */` comment followed by a single @font-face
    # block. Pull only the `latin` ones.
    pattern = re.compile(
        r'/\*\s*([^*]+?)\s*\*/\s*(@font-face\s*\{[^}]+\})', re.DOTALL,
    )

    blocks: list[str] = []
    for m in pattern.finditer(css):
        subset = m.group(1).strip()
        block = m.group(2)
        if subset != 'latin':
            continue

        url = re.search(r'src:\s*url\(([^)]+)\)', block).group(1)
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r'font-weight:\s*(\d+)', block).group(1)

        safe = family.lower().replace(' ', '-')
        fname = f'{safe}-{weight}.woff2'
        dest = os.path.join(FONTS_DIR, fname)
        with urllib.request.urlopen(url) as r, open(dest, 'wb') as f:
            f.write(r.read())
        size_kb = os.path.getsize(dest) // 1024
        print(f'  fetched {fname} ({size_kb} KB)', file=sys.stderr)

        # Rewrite the URL to a Vite-served absolute path. Files in public/
        # are served from the site root in dev and copied verbatim into
        # dist/ at build time.
        local_block = block.replace(url, f'/fonts/{fname}')
        blocks.append(local_block)

    header = (
        '/* Auto-generated by scripts/fetch-fonts.py. Do not edit by hand. */\n'
        '/* Inter Tight (sans), Source Serif 4 (serif), JetBrains Mono (mono). */\n'
    )
    with open(OUT_CSS, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
        f.write('\n'.join(blocks) + '\n')
    print(f'wrote {OUT_CSS}', file=sys.stderr)


if __name__ == '__main__':
    main()
